name: bedrock
recipe: wordpress
config:
  php: '7.2'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true
services:
  node:
    type: node
    globals:
      gulp-cli: "latest"
      bower: "latest"
      webpack: "latest"
      npm: "latest"

tooling:
  npm:
    service: node